config/routes.rb
Rails.application.routes.draw do
  root to:'bookers#top'
  get 'books' => 'bookers#index'
  post 'books' => 'bookers#create'
  get 'books/:id' => 'bookers#show', as:'show_book'
  get 'books/:id/edit' => 'bookers#edit', as:'edit_book'
  patch 'books/:id' => 'bookers#update', as:'update_book'
  delete 'books/:id' => 'bookers#destroy', as:'destroy_book'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookers_controller.rb
class BookersController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all

  end

  def create
    @book = Book.new(book_params)
    if @book.save
    flash[:noice] = "Book was successfully created."
    redirect_to show_book_path(@book.id)
    else
    @books = Book.all
    render "index"
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:noice] = "Book was successfully updated."
    redirect_to show_book_path(@book.id)
    else
    @books = Book.all
    render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
    flash[:noice] = "Book was successfully destroyed."
    redirect_to '/books'
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/views/bookers/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <div id="error_explanation">
  <% error_count = @book.errors.count %>
  <h2><%= error_count %> <%= 'error'.pluralize(error_count) %> prohibited this book from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
    <form_edit>
    <div class="field">
    <la>Title</la>
    <%= f.text_field :title %>
    </div>
    <div class="field">
    <la>Body</la>
    <%= f.text_area :body %>
    </div>
    <div class="action"><%= f.submit 'Update Book' %></div>
    </form_edit>
<% end %>
  <p>
  <%= link_to "Show", show_book_path(@book.id) %>
   |
  <%= link_to "Back", "/books" %>
  </p>

app/views/bookers/index.html.erb
<h1>Books</h1>
  <table>
    <thead>
    <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", show_book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

<h2>New book</h2>

<body_form>
<% if @book.errors.any? %>
  <div id="error_explanation">
  <% error_count = @book.errors.count %>
  <h2><%= error_count %> <%= 'error'.pluralize(error_count) %> prohibited this book from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

<%= form_with model: Book.new do |f| %>
  <div class="field">
  <la>Title</la>
  <%= f.text_field :title %>
  </div>
  <div class="field">
  <la>Body</la>
  <%= f.text_area :body %>
  </div>
  <div class="action"><%= f.submit 'Create Book' %></div>
<% end %>
</body_form>

app/views/bookers/show.html.erb
<body_show>

  <pp><strong>Title: </strong><%= @book.title %></pp>
  <pp><strong>Body: </strong><%= @book.body %></pp>

</body_show>

  <p>
  <%= link_to "Edit", edit_book_path(@book.id) %>
   |
  <%= link_to "Back", "/books" %>
  </p>

app/views/bookers/top.html.erb
<h1>ようこそ Bookersへ！</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><%= link_to "start", "/books" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
    <div class="notice <%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>